"""empty message

Revision ID: 0f709f68fae3
Revises: 4c38a4278c1e
Create Date: 2020-12-27 16:56:29.802281

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0f709f68fae3'
down_revision = '4c38a4278c1e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('environment', sa.Column('name', sa.String(length=100, collation='utf8_general_ci'), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('environment', 'name')
    # ### end Alembic commands ###
