"""empty message

Revision ID: 4c38a4278c1e
Revises: 9be854994aac
Create Date: 2020-12-24 01:09:24.712169

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4c38a4278c1e'
down_revision = '9be854994aac'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('admin',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('first_name', sa.String(length=20, collation='utf8_general_ci'), nullable=False),
    sa.Column('last_name', sa.String(length=20, collation='utf8_general_ci'), nullable=False),
    sa.Column('password', sa.String(length=100, collation='utf8_general_ci'), nullable=False),
    sa.Column('email', sa.String(length=100, collation='utf8_general_ci'), nullable=False),
    sa.Column('tc_number', sa.String(length=11, collation='utf8_general_ci'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('appointment',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('start', sa.DateTime(), nullable=False),
    sa.Column('end', sa.DateTime(), nullable=False),
    sa.Column('description', sa.String(length=1000, collation='utf8_general_ci'), nullable=False),
    sa.Column('environment_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['environment_id'], ['environment.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('environment_admin',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('environment_id', sa.Integer(), nullable=False),
    sa.Column('admin_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['admin_id'], ['admin.id'], ),
    sa.ForeignKeyConstraint(['environment_id'], ['environment.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('environment_working_hour',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('start', sa.DateTime(), nullable=False),
    sa.Column('end', sa.DateTime(), nullable=False),
    sa.Column('environment_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['environment_id'], ['environment.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('environment_working_hour')
    op.drop_table('environment_admin')
    op.drop_table('appointment')
    op.drop_table('admin')
    # ### end Alembic commands ###
