"""empty message

Revision ID: dcd7be474216
Revises: 0f709f68fae3
Create Date: 2021-01-10 16:09:42.089254

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'dcd7be474216'
down_revision = '0f709f68fae3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('appointment', sa.Column('is_accepted', sa.Boolean(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('appointment', 'is_accepted')
    # ### end Alembic commands ###
